// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/WebCraftersGH/Auth-service/internal/contracts (interfaces: OTPsRepo)
//
// Generated by this command:
//
//	mockgen -destination mocks/otpsRepo_mock.go -package mocks github.com/WebCraftersGH/Auth-service/internal/contracts OTPsRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/WebCraftersGH/Auth-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOTPsRepo is a mock of OTPsRepo interface.
type MockOTPsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOTPsRepoMockRecorder
	isgomock struct{}
}

// MockOTPsRepoMockRecorder is the mock recorder for MockOTPsRepo.
type MockOTPsRepoMockRecorder struct {
	mock *MockOTPsRepo
}

// NewMockOTPsRepo creates a new mock instance.
func NewMockOTPsRepo(ctrl *gomock.Controller) *MockOTPsRepo {
	mock := &MockOTPsRepo{ctrl: ctrl}
	mock.recorder = &MockOTPsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPsRepo) EXPECT() *MockOTPsRepoMockRecorder {
	return m.recorder
}

// DeleteCode mocks base method.
func (m *MockOTPsRepo) DeleteCode(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCode", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCode indicates an expected call of DeleteCode.
func (mr *MockOTPsRepoMockRecorder) DeleteCode(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCode", reflect.TypeOf((*MockOTPsRepo)(nil).DeleteCode), key)
}

// GetCode mocks base method.
func (m *MockOTPsRepo) GetCode(key string) (domain.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", key)
	ret0, _ := ret[0].(domain.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockOTPsRepoMockRecorder) GetCode(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockOTPsRepo)(nil).GetCode), key)
}

// IncAttempts mocks base method.
func (m *MockOTPsRepo) IncAttempts(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncAttempts", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncAttempts indicates an expected call of IncAttempts.
func (mr *MockOTPsRepoMockRecorder) IncAttempts(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncAttempts", reflect.TypeOf((*MockOTPsRepo)(nil).IncAttempts), key)
}

// SaveCode mocks base method.
func (m *MockOTPsRepo) SaveCode(otp domain.OTP, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCode", otp, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCode indicates an expected call of SaveCode.
func (mr *MockOTPsRepoMockRecorder) SaveCode(otp, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCode", reflect.TypeOf((*MockOTPsRepo)(nil).SaveCode), otp, key)
}
